### ISSUE TITLE
Error while loading shared libraries (libldap)

### ISSUE THREAD

**Issue by h6y34ui98** [DeckerSU/KomodoOcean#36]
Seems like the newer version of libldap doesn't work with komodo-qt-linux. Any thoughts?

`./komodo-qt-linux &`
>[1] 8439
./komodo-qt-linux: error while loading shared libraries: **libldap_r-2.4.so.2**: cannot open shared object file: No such file or directory
[1]+  Exit 127                ./komodo-qt-linux

 `ldd komodo-qt-linux`
>	linux-vdso.so.1 (0x00007ffdcfcc3000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f27ec4ea000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f27ec4df000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f27ec4b5000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f27ec466000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f27ec39b000)
	librtmp.so.1 => /usr/lib/librtmp.so.1 (0x00007f27ec37c000)
	**libldap_r-2.4.so.2 => not found
	liblber-2.4.so.2 => not found**
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f27ec359000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f27ec352000)
	libanl.so.1 => /usr/lib/libanl.so.1 (0x00007f27ec34b000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f27ec207000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f27ec1c1000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f27ec1a6000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f27ebfda000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f27ef04b000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f27ebfd5000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f27ebfcd000)
	libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f27ebf9d000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f27ebf81000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f27ebf6e000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f27ebf37000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f27ebe5e000)
	libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007f27ebe50000)
	libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x00007f27ebc4f000)
	libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x00007f27ebc04000)
	libnettle.so.8 => /usr/lib/libnettle.so.8 (0x00007f27ebbbd000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f27ebb1d000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f27ebaf8000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f27eb9c2000)
	libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007f27eb99d000)
	libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x00007f27eb868000)
	libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f27eb846000)
	libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007f27eb6c4000)
	libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007f27eb6ae000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f27eb637000)
	libffi.so.8 => /usr/lib/libffi.so.8 (0x00007f27eb629000)

`yay libldap`
>warning: **libldap-2.6.0-2 is up to date** -- reinstalling
resolving dependencies...
looking for conflicting packages...
Packages (1) libldap-2.6.0-2
Total Installed Size:  0.65 MiB
Net Upgrade Size:      0.00 MiB

**Comment by DeckerSU** [comment]
It's about ArchLinux? Seems you have two options:

- Try to build Komodo-Qt (KomodoOcean) from sources under your OS
- Try to use [latest binaries](https://github.com/DeckerSU/KomodoOcean/releases/tag/v0.7.1-beta3) compiled with GLIBC 2.31

**Comment by h6y34ui98** [comment]
Thanks for responding. I chose the lazy way using the latest binaries and can confirm it's working nicely. All good :-)
